name: thoitrang
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=2.19.2 <3.0.0"
    flutter: ">=3.0.0"
dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    google_fonts: ^4.0.3
    carousel_slider: ^4.2.1
    flutter_layout_grid: ^2.0.0
    intl: ^0.18.0
    go_router: ^6.0.9
    animated_size_and_fade: ^3.0.1
    flutter_riverpod: ^2.1.3
    riverpod_annotation: ^1.1.1
    mask_text_input_formatter: ^2.4.0
    formz: ^0.4.1
    equatable: ^2.0.5
    flutter_dropdown_alert: ^1.0.7
    pin_code_fields: ^7.4.0
    dio: ^5.0.1
    photo_view: ^0.14.0
    custom_navigation_bar: ^0.8.2
    flutter_svg: ^2.0.2
    freezed_annotation: ^2.2.0
    json_annotation: ^4.8.0
    flutter_rating_bar: ^4.0.1
    unique_identifier: ^0.3.0
    platform_device_id: ^1.0.1
    another_xlider: ^1.1.2
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.3.3
    freezed: ^2.3.2
    json_serializable: ^6.6.1
    hive_generator: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/
        - assets/rive/

    fonts:
        - family: AppFonts
          fonts:
              - asset: assets/fonts/icons/AppFonts.ttf
        - family: UA
          fonts:
              - asset: assets/fonts/UTM Avo.ttf
        - family: UAB
          fonts:
              - asset: assets/fonts/UTM AvoBold.ttf